version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
